from tiles import *

THEMES = [
    {
        "name": "Classic Monopoly",
        "description": "The classic Monopoly board with traditional properties and cards.",
        "map": [
            Go("Go"),
            Property("Mediterranean Avenue", "Brown", 60),
            CardTile("Community Chest", group="Community Chest"),
            Property("Baltic Avenue", "Brown", 60),
            Tax("Income Tax", 200),
            Railroad("Reading Railroad", 200),
            Property("Oriental Avenue", "Light Blue", 100),
            CardTile("Chance", group="Chance"),
            Property("Vermont Avenue", "Light Blue", 100),
            Property("Connecticut Avenue", "Light Blue", 100),
            Jail("Jail"),
            Property("St.Charles Place", "Pink", 140),
            Utility("Electric Company", 150),
            Property("States Avenue", "Pink", 140),
            Property("Virginia Avenue", "Pink", 160),
            Railroad("Pennsylvania Railroad", 200),
            Property("St. James Place", "Orange", 180),
            CardTile("Community Chest", group="Community Chest"),
            Property("Tennessee Avenue", "Orange", 180),
            Property("New York Avenue", "Orange", 200),
            Tile("Free Parking"),
            Property("Kentucky Avenue", "Red", 220),
            CardTile("Chance", group="Chance"),
            Property("Indiana Avenue", "Red", 220),
            Property("Illinois Avenue", "Red", 240),
            Railroad("B&O Railroad", 200),
            Property("Atlantic Avenue", "Yellow", 260),
            Property("Ventnor Avenue", "Yellow", 260),
            Utility("Water Works", 150),
            Property("Marvin Gardens", "Yellow", 280),
            GoToJail("Go to Jail"),
            Property("Pacific Avenue", "Green", 300),
            Property("N.Carolina Avenue", "Green", 300),
            CardTile("Community Chest", group="Community Chest"),
            Property("Pennsylvania Avenue", "Green", 320),
            Railroad("Short Line", 200),
            CardTile("Chance", group="Chance"),
            Property("Park Place", "Dark Blue", 350),
            Tax("Luxury Tax", 100),
            Property("Boardwalk", "Dark Blue", 400)
        ],
        "Chance": [
            ("Advance to Go (Collect $200).", 'move', 0),
            ("Go to Jail. Do not pass Go.", 'jail'),
            ("Bank pays you dividend of $50.", "money", 50),
            ("Get Out of Jail Free.", "item", "Get Out of Jail Free Card"),
            ("Go back 3 spaces.", "move_relative", -3),
            ("Speeding fine $15.", "money", -15),
            ("You have been elected Chairman of the Board. Pay $50.", "money", -50),
            ("Building loan matures. Collect $150.", "money", 150)
        ],
        "Community Chest": [
            ("Advance to Go (Collect $200).", "move", 0),
            ("Bank error in your favor. Collect $200.", "money", 200),
            ("Doctor's fee. Pay $50.", "money", -50),
            ("From sale of stock you get $50.", "money", 50),
            ("Get Out of Jail Free.", "item", "Get Out of Jail Free Card"),
            ("Go to Jail. Do not pass Go.", "jail"),
            ("Life insurance matures. Collect $100.", "money", 100),
            ("Pay hospital fees of $100.", "money", -100),
            ("Receive $25 consultancy fee.", "money", 25),
            ("You inherit $100.", "money", 100)
        ]
    },
    {
        "name": "Star Wars",
        "description": "A Star Wars-themed Monopoly board.",
        "map": [
            Go("Go"),
            Property("Owen's Homestead", "Brown", 80),
            Property("Mos Eisley Cantina", "Brown", 100),
            Tax("Imperial Tax", 250),
            Property("Hoth Wasteland", "Light Blue", 120),
            Property("Echo Base", "Light Blue", 140),
            Property("Wampa Cave", "Light Blue", 140),
            CardTile("Jedi Holocron", group="Community Chest"),
            CardTile("Force Vision", group="Chance"),
            Railroad("Millennium Falcon", 250),
            Jail("Detention Block"),
            Railroad("X-Wing", 250),
            Utility("Power Converters", 150),
            Utility("Moisture Vaporator", 150),
            Property("Yavin 4 Swamp", "Pink", 180),
            Property("Massassi Temple", "Pink", 180),
            Property("Rebel Base", "Pink", 200),
            CardTile("Jedi Holocron", group="Community Chest"),
            Property("Dagobah Swamp", "Orange", 220),
            Property("Yoda's Hut", "Orange", 220),
            Tile("Safe Haven"),
            Property("Dark Cave", "Orange", 240),
            Property("Cloud City", "Red", 260),
            Property("Carbonite Chamber", "Red", 260),
            Property("Bespin Platform", "Red", 280),
            Tax("Sith Tax", 200),
            CardTile("Force Vision", group="Chance"),
            Railroad("TIE Fighter", 250),
            Property("Asteroid Belt", "Yellow", 300),
            Property("Giant Worm Thing", "Yellow", 300),
            GoToJail("Captured by Sith!"),
            Property("Shield Generator", "Yellow", 320),
            CardTile("Jedi Holocron", group="Community Chest"),
            Property("Endor Forest", "Green", 350),
            Property("Ewok Village", "Green", 350),
            Property("Shield Generator", "Green", 380),
            CardTile("Force Vision", group="Chance"),
            Railroad("Star Destroyer", 250),
            Property("Death Star", "Dark Blue", 450),
            Property("Death Star II", "Dark Blue", 500)
        ],
        "Chance": [
            ("Smuggling run successful! Collect $150.", "money", 150),
            ("Hyperdrive broken. Pay $50 for repairs.", "money", -50),
            ("Imperial Entanglements! Go to Detention Block.", "jail"),
            ("The Force is with you! Advance to Go.", "move", 0),
            ("Evade Star Destroyer! Go back 3 spaces.", "move_relative", -3),
            ("Jedi Mind Trick! (Get Out of Jail Free).", "item", "Get Out of Jail Free Card")
        ],
        "Community Chest": [
            ("Found hidden credits. Collect $200.", "money", 200),
            ("Bounty collected. Get $50.", "money", 50),
            ("Cantina tab due. Pay $50.", "money", -50),
            ("Sith ambush! Go to Detention Block.", "jail"),
            ("Force Ghost guide! Advance to Go.", "move", 0),
            ("Jedi Mind Trick! (Get Out of Jail Free).", "item", "Get Out of Jail Free Card")
        ]
    },
    {
        "name": "Minecraft",
        "description": "A Minecraft-themed Monopoly board.",
        "map": [
            Go("Spawn Point"),
            Property("Dirt", "Brown", 60),
            CardTile("Bonus Chest", group="Community Chest"),
            Property("Cobblestone", "Brown", 60),
            Tax("Creeper Blast", 150),
            Railroad("Horse", 200),
            Property("Birch Forest", "Light Blue", 90),
            CardTile("Loot Map", group="Chance"),
            Property("Oak Forest", "Light Blue", 90),
            Property("Spruce Forest", "Light Blue", 110),
            Jail("Dungeon"),
            Property("Desert Village", "Pink", 130),
            Utility("Redstone Circuit", 150),
            Property("Desert Temple", "Pink", 130),
            Property("Badlands", "Pink", 150),
            Railroad("Boat", 200),
            Property("Jungle Biome", "Orange", 170),
            CardTile("Bonus Chest", group="Community Chest"),
            Property("Bambo Jungle", "Orange", 170),
            Property("Lush Caves", "Orange", 190),
            Tile("AFK Base"),
            Property("Snowy Tundra", "Red", 210),
            CardTile("Loot Map", group="Chance"),
            Property("Ice Spikes", "Red", 210),
            Property("Taiga Village", "Red", 230),
            Railroad("Minecart", 200),
            Property("Nether Wastes", "Yellow", 250),
            Property("Crimson Forest", "Yellow", 250),
            Utility("Water Source", 150),
            Property("Bastion Remnant", "Yellow", 270),
            GoToJail("Go to Dungeon"),
            Property("Warped Forest", "Green", 290),
            Property("Soul Sand Valley", "Green", 290),
            CardTile("Bonus Chest", group="Community Chest"),
            Property("Nether Fortress", "Green", 310),
            Railroad("Elytra", 200),
            CardTile("Loot Map", group="Chance"),
            Property("The End Island", "Dark Blue", 350),
            Tax("Wither Attack", 100),
            Property("End City", "Dark Blue", 400)
        ],
        "Chance": [
            ("Looted a Desert Temple! Collect $150.", "money", 150),
            ("Skeleton shot you! Pay $50 to heal.", "money", -50),
            ("Captured by Illagers! Go to Cage.", "jail"),
            ("Follow Map! Advance to Spawn Point.", "move", 0),
            ("Lost in the woods! Go back 3 spaces.", "move_relative", -3),
            ("Ender Pearl! (Get Out of Jail Free).", "item", "Get Out of Jail Free Card")
        ],
        "Community Chest": [
            ("Found Diamonds! Collect $200.", "money", 200),
            ("Traded with Villagers! Collect $50.", "money", 50),
            ("Creeper blew up your chest! Pay $50.", "money", -50),
            ("Fell into a hole! Go to Cobweb Cage.", "jail"),
            ("Respawn! (Advance to Spawn Point).", "move", 0),
            ("Ender Pearl! (Get Out of Jail Free).", "item", "Get Out of Jail Free Card")
        ]
    },
    {
        "name": "Hardcore Monopoly",
        "description": "A more challenging version of Monopoly with higher rents and tougher cards.",
        "map": [
            Go("Go"),
            Property("Mediterranean Avenue", "Brown", 120),
            CardTile("Community Chest", group="Community Chest"),
            Property("Baltic Avenue", "Brown", 120),
            Tax("Income Tax", 400),
            Railroad("Reading Railroad", 400),
            Property("Oriental Avenue", "Light Blue", 200),
            CardTile("Chance", group="Chance"),
            Property("Vermont Avenue", "Light Blue", 200),
            Property("Connecticut Avenue", "Light Blue", 200),
            Jail("Jail"),
            Property("St.Charles Place", "Pink", 280),
            Utility("Electric Company", 300),
            Property("States Avenue", "Pink", 280),
            Property("Virginia Avenue", "Pink", 320),
            Railroad("Pennsylvania Railroad", 400),
            Property("St. James Place", "Orange", 360),
            CardTile("Community Chest", group="Community Chest"),
            Property("Tennessee Avenue", "Orange", 360),
            Property("New York Avenue", "Orange", 400),
            Tile("Free Parking"),
            Property("Kentucky Avenue", "Red", 440),
            CardTile("Chance", group="Chance"),
            Property("Indiana Avenue", "Red", 440),
            Property("Illinois Avenue", "Red", 480),
            Railroad("B&O Railroad", 400),
            Property("Atlantic Avenue", "Yellow", 520),
            Property("Ventnor Avenue", "Yellow", 520),
            Utility("Water Works", 300),
            Property("Marvin Gardens", "Yellow", 560),
            GoToJail("Go to Jail"),
            Property("Pacific Avenue", "Green", 600),
            Property("N.Carolina Avenue", "Green", 600),
            CardTile("Community Chest", group="Community Chest"),
            Property("Pennsylvania Avenue", "Green", 640),
            Railroad("Short Line", 400),
            CardTile("Chance", group="Chance"),
            Property("Park Place", "Dark Blue", 700),
            Tax("Luxury Tax", 200),
            Property("Boardwalk", "Dark Blue", 800)
        ],
        "Chance": [
            ("Advance to Go (Collect $200).", 'move', 0),
            ("Go to Jail. Do not pass Go.", 'jail'),
            ("Bank pays you dividend of $50.", 'money', 50),
            ("Get Out of Jail Free.", 'item', 'Get Out of Jail Free Card'),
            ("Go back 3 spaces.", 'move_relative', -3),
            ("Speeding fine $15.", 'money', -15),
            ("You have been elected Chairman of the Board. Pay $50.", 'money', -50),
            ("Building loan matures. Collect $150.", 'money', 150)
        ],
        "Community Chest": [
            ("Advance to Go (Collect $200).", 'move', 0),
            ("Bank error in your favor. Collect $200.", 'money', 200),
            ("Doctor's fee. Pay $50.", 'money', -50),
            ("From sale of stock you get $50.", 'money', 50),
            ("Get Out of Jail Free.", 'item', 'Get Out of Jail Free Card'),
            ("Go to Jail. Do not pass Go.", 'jail'),
            ("Life insurance matures. Collect $100.", 'money', 100),
            ("Pay hospital fees of $100.", 'money', -100),
            ("Receive $25 consultancy fee.", 'money', 25),
            ("You inherit $100.", 'money', 100)
        ]
    }
]